"""remove ticker

Revision ID: 0e506649b639
Revises: c34becfbbc74
Create Date: 2025-03-29 21:58:44.915887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e506649b639'
down_revision: Union[str, None] = 'c34becfbbc74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'ticker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ticker', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
