"""added ticker to order table

Revision ID: c34becfbbc74
Revises: 72e3ae7aa9c6
Create Date: 2025-03-29 21:50:45.713079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34becfbbc74'
down_revision: Union[str, None] = '72e3ae7aa9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ticker', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'ticker')
    # ### end Alembic commands ###
