"""added user questionnaire

Revision ID: ccded886f1eb
Revises: 7514d85feade
Create Date: 2025-03-30 00:48:21.876835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccded886f1eb'
down_revision: Union[str, None] = '7514d85feade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_experienced_investor', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('preferred_sectors', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('sector_preference_rankings', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('market_cap_preference', sa.Enum('SMALL_CAP', 'MID_CAP', 'LARGE_CAP', 'MIXED', name='marketcappreferences'), nullable=True))
    op.add_column('users', sa.Column('growth_vs_value', sa.Enum('GROWTH', 'VALUE', 'BLEND', name='growthvsvalue'), nullable=True))
    op.add_column('users', sa.Column('cyclical_vs_defensive', sa.Enum('CYCLICAL', 'DEFENSIVE', 'MIXED', name='cyclicalvsdefensive'), nullable=True))
    op.add_column('users', sa.Column('valuation_metrics_preference', sa.Enum('PE_RATIO', 'PB_RATIO', 'PS_RATIO', 'EV_EBITDA', 'DIVIDEND_YIELD', 'ROE', 'ROA', 'PROFIT_MARGIN', name='valuationmetricspreference'), nullable=True))
    op.add_column('users', sa.Column('dividend_preference', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tech_sector_interest', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('healthcare_sector_interest', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('financial_sector_interest', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('energy_sector_interest', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('consumer_goods_sector_interest', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('industrials_sector_interest', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('emerging_markets_interest', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('esg_preference', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('small_cap_interest', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('blue_chip_interest', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tech_subsectors_interest', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('healthcare_subsectors_interest', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('investment_time_horizon', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('has_trade_history', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_trade_history')
    op.drop_column('users', 'investment_time_horizon')
    op.drop_column('users', 'healthcare_subsectors_interest')
    op.drop_column('users', 'tech_subsectors_interest')
    op.drop_column('users', 'blue_chip_interest')
    op.drop_column('users', 'small_cap_interest')
    op.drop_column('users', 'esg_preference')
    op.drop_column('users', 'emerging_markets_interest')
    op.drop_column('users', 'industrials_sector_interest')
    op.drop_column('users', 'consumer_goods_sector_interest')
    op.drop_column('users', 'energy_sector_interest')
    op.drop_column('users', 'financial_sector_interest')
    op.drop_column('users', 'healthcare_sector_interest')
    op.drop_column('users', 'tech_sector_interest')
    op.drop_column('users', 'dividend_preference')
    op.drop_column('users', 'valuation_metrics_preference')
    op.drop_column('users', 'cyclical_vs_defensive')
    op.drop_column('users', 'growth_vs_value')
    op.drop_column('users', 'market_cap_preference')
    op.drop_column('users', 'sector_preference_rankings')
    op.drop_column('users', 'preferred_sectors')
    op.drop_column('users', 'is_experienced_investor')
    # ### end Alembic commands ###
